[program:fx0093]
command=/usr/bin/ffmpeg -user_agent "Mozilla/5.0" -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 -i https://FUENTE_PROVEEDOR/live/USUARIO/TOKEN/CANAL.ts -c:v copy -c:a aac -strict -2 -f flv rtmp://127.0.0.1:1936/live/fx0093
autostart=true
autorestart=true
startsecs=20
startretries=999
exitcodes=0
stopsignal=INT
user=root
stdout_logfile=/var/log/supervisor/fx0093.out.log
stderr_logfile=/var/log/supervisor/fx0093.err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=HOME="/root"
